---
version: '2.2'
services:
  synchronizer:
    build:
      context: synchronizer
    container_name: synchronizer
    environment:
      KAFKA_BROKERS: "kafka:19092"
      SCHEMA_REGISTRY_URL: "http://schema-registry:18081"
    logging:
      driver: none
