@startuml

title Command generator

package "nl.openweb.command-generator.core.clj" #Yellow {
    component accounts as a
    component consumer as c
    component producer as p
}
[Kafka cluster] as kc #Orange

c -> a  :update ibans used
a --> p  :used to generate\ltransfers
c -> p :trigger\lcommand generation
p -> kc :produces\lConfirmAccountCreation\nand\nConfirmMoneyTransfer
c <-- kc :consumes\lHeartbeat\nand\nConfirmAccountCreation

@enduml