@startuml

title Command handler

package "nl.openweb.command-handler.core.clj" #Yellow {
    component "cmt-handler" as mth
    component "cac-handler" as ach
    component consumer as c
    component producer as p
}
package balancedb #LightBlue{
    database balance
    database cac
    database cmt
}
[Kafka cluster] as kc #Orange

mth --> cmt :check/update status
ach --> cac :check/update status
mth --> balance :check/update balance
ach --> balance :crates balance
p --> kc :AccountCreationConfirmed,\nAccountCreationFailed,\nMoneyTransferConfirmed,\nMoneyTransferFailed and\nBalanceChanged
c <-- kc :ConfirmAccountCreation\n and ConfirmMoneyTransfer

@enduml