@startuml
left to right direction
title All connections
[Kafka cluster] as kc #Orange
[Zookeeper cluster] as zc #Green
[Schema registry] as sr
[Synchronizer] as sy
[Heartbeat] as hb
[Command generator] as cg
[Command handler] as ch
[GraphQL endpoint] as ge
[Frontend server] as fs
actor client as cl
database balancedb as pgb
database transactiondb as pgt

kc ..> zc : get and set meta data
sy ..> kc : creates topics
sy ..> sr : set schemas
sr --> kc : store schemas
hb --> sr : get schemas
cg --> sr : get schemas
ch --> sr : get schemas
ge --> sr : get schemas
hb --> kc : produces Heartbeat
kc --> cg : consumes Heartbeat
cg --> kc : produces ConfirmAccountCreation\n and ConfirmMoneyTransfer
kc --> ch : consumes ConfirmAccountCreation\n and ConfirmMoneyTransfer
ch --> kc : produces AccountCreationConfirmed,\nAccountCreationFailed,\nMoneyTransferConfirmed,\nMoneyTransferFailed and\nBalanceChanged
kc --> ge : consumes ConfirmAccountCreation,\nConfirmMoneyTransfer and\nBalanceChanged
ge --> kc : produces ConfirmAccountCreation\n and ConfirmMoneyTransfer
fs --> cl : provides frontend code
cl --> ge : create accounts and transactions
ge --> cl : provides information
pgb <--> ch : keep track witch messages have been handled\nkeep the balances
pgt <--> ge : stores/queries transactions

@enduml